# Generated by Django 6.0 on 2025-12-15 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('semestre_actuel', models.IntegerField(default=1)),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluerose.parcours')),
            ],
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('intitule', models.CharField(max_length=300)),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('semeste', models.IntegerField(blank=True, null=True)),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluerose.parcours')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluerose.etudiant')),
                ('PROFESSUER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluerose.professeur')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bluerose.ue')),
            ],
        ),
    ]
